//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPortal.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevPortal.Resources.Resources.PropertyNames", typeof(PropertyNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama Grubu.
        /// </summary>
        public static string ApplicationGroupId {
            get {
                return ResourceManager.GetString("ApplicationGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama Grubu Adı.
        /// </summary>
        public static string ApplicationGroupName {
            get {
                return ResourceManager.GetString("ApplicationGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama Grubu Durumu.
        /// </summary>
        public static string ApplicationGroupStatusId {
            get {
                return ResourceManager.GetString("ApplicationGroupStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama.
        /// </summary>
        public static string ApplicationId {
            get {
                return ResourceManager.GetString("ApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama Adı.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama Durumu.
        /// </summary>
        public static string ApplicationStatusId {
            get {
                return ResourceManager.GetString("ApplicationStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama Tipi.
        /// </summary>
        public static string ApplicationTypeId {
            get {
                return ResourceManager.GetString("ApplicationTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama Başarılı Versiyon Paketleri PreProd Dizini.
        /// </summary>
        public static string ApplicationVersionPackagePreProdFolderPath {
            get {
                return ResourceManager.GetString("ApplicationVersionPackagePreProdFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama Başarılı Versiyon Paketleri Prod Dizini.
        /// </summary>
        public static string ApplicationVersionPackageProdFolderPath {
            get {
                return ResourceManager.GetString("ApplicationVersionPackageProdFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derleme Tipi.
        /// </summary>
        public static string BuildTypeId {
            get {
                return ResourceManager.GetString("BuildTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola Tekrar.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı Aktarım Paketleri PreProd Dizini.
        /// </summary>
        public static string DatabaseDeploymentPackagePreProdFolderPath {
            get {
                return ResourceManager.GetString("DatabaseDeploymentPackagePreProdFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı Aktarım Paketleri Prod Dizini.
        /// </summary>
        public static string DatabaseDeploymentPackageProdFolderPath {
            get {
                return ResourceManager.GetString("DatabaseDeploymentPackageProdFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı Grubu.
        /// </summary>
        public static string DatabaseGroupId {
            get {
                return ResourceManager.GetString("DatabaseGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı Tipi.
        /// </summary>
        public static string DatabaseTypeId {
            get {
                return ResourceManager.GetString("DatabaseTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Yolu.
        /// </summary>
        public static string DeployPath {
            get {
                return ResourceManager.GetString("DeployPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta Adresi.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ortam.
        /// </summary>
        public static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ortam.
        /// </summary>
        public static string EnvironmentId {
            get {
                return ResourceManager.GetString("EnvironmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağımlılık Adı.
        /// </summary>
        public static string ExternalDependencyName {
            get {
                return ResourceManager.GetString("ExternalDependencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İkon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jenkins Görevi Adı.
        /// </summary>
        public static string JenkinsJobName {
            get {
                return ResourceManager.GetString("JenkinsJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jenkins Görev Tipi.
        /// </summary>
        public static string JenkinsJobType {
            get {
                return ResourceManager.GetString("JenkinsJobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jenkins Url.
        /// </summary>
        public static string JenkinsUrl {
            get {
                return ResourceManager.GetString("JenkinsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görev Türü.
        /// </summary>
        public static string JobTypeId {
            get {
                return ResourceManager.GetString("JobTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Dizini Yolu.
        /// </summary>
        public static string LogFilePath {
            get {
                return ResourceManager.GetString("LogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü Grubu.
        /// </summary>
        public static string MenuGroup {
            get {
                return ResourceManager.GetString("MenuGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Parola.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveBuilder Nuget ApiKey.
        /// </summary>
        public static string NugetApiKey {
            get {
                return ResourceManager.GetString("NugetApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveBuilder Nuget Paket Arşivi Dizini.
        /// </summary>
        public static string NugetPackageArchiveFolderPath {
            get {
                return ResourceManager.GetString("NugetPackageArchiveFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuget Paket Adı.
        /// </summary>
        public static string NugetPackageName {
            get {
                return ResourceManager.GetString("NugetPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveBuilder NuGet Url.
        /// </summary>
        public static string NugetUrl {
            get {
                return ResourceManager.GetString("NugetUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Adı.
        /// </summary>
        public static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Url.
        /// </summary>
        public static string PageUrl {
            get {
                return ResourceManager.GetString("PageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiziksel Yol.
        /// </summary>
        public static string PhysicalPath {
            get {
                return ResourceManager.GetString("PhysicalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Adı.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yayınlama Profil Adı.
        /// </summary>
        public static string ProjectPublishProfileName {
            get {
                return ResourceManager.GetString("ProjectPublishProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dizin Adresi.
        /// </summary>
        public static string ProjectRemoteAddress {
            get {
                return ResourceManager.GetString("ProjectRemoteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine Proje Adı.
        /// </summary>
        public static string RedmineProjectName {
            get {
                return ResourceManager.GetString("RedmineProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine Url.
        /// </summary>
        public static string RedmineUrl {
            get {
                return ResourceManager.GetString("RedmineUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solüsyon Adı.
        /// </summary>
        public static string SolutionName {
            get {
                return ResourceManager.GetString("SolutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube Proje Adı.
        /// </summary>
        public static string SonarqubeProjectName {
            get {
                return ResourceManager.GetString("SonarqubeProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube Proje Tipi.
        /// </summary>
        public static string SonarqubeProjectType {
            get {
                return ResourceManager.GetString("SonarqubeProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube Url.
        /// </summary>
        public static string SonarQubeUrl {
            get {
                return ResourceManager.GetString("SonarQubeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svn Açıklama.
        /// </summary>
        public static string SvnDescription {
            get {
                return ResourceManager.GetString("SvnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svn Adı.
        /// </summary>
        public static string SvnName {
            get {
                return ResourceManager.GetString("SvnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depo Adı.
        /// </summary>
        public static string SvnRepositoryFolderName {
            get {
                return ResourceManager.GetString("SvnRepositoryFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svn Depo Tipi.
        /// </summary>
        public static string SvnRepositoryType {
            get {
                return ResourceManager.GetString("SvnRepositoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svn Url.
        /// </summary>
        public static string SvnUrl {
            get {
                return ResourceManager.GetString("SvnUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svn Kullanıcı Adı.
        /// </summary>
        public static string SvnUserName {
            get {
                return ResourceManager.GetString("SvnUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama Ortamı Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Durumu.
        /// </summary>
        public static string UserStatusId {
            get {
                return ResourceManager.GetString("UserStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Tipi.
        /// </summary>
        public static string UserTypeId {
            get {
                return ResourceManager.GetString("UserTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Alanı.
        /// </summary>
        public static string Workspace {
            get {
                return ResourceManager.GetString("Workspace", resourceCulture);
            }
        }
    }
}
